import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/template/Layout'
import { Typography } from 'antd';
import CardGrid from '../components/template/CardGrid';
import { useCallback, useEffect, useState } from 'react';
import { getAnimes } from '../data/apiClient';

const { Title } = Typography;

const Home: NextPage = () => {
  const [animes, setAnimes] = useState<any>()

  console.log(animes)

  useEffect(() => {
    (async function () {
      setAnimes(await getAnimes())
    })()    
  }, [])

  useEffect(() => console.log(animes), [animes])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
        <Title>Fique por dentro do que há de melhor no mundo dos animes</Title>
        <CardGrid data={animes} />
      </Layout>
      
    </div>
  )
}

export default Home
