import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/template/Layout'
import { Button, Typography } from 'antd';
import CardGrid from '../components/template/CardGrid';
import useAppData from '../data/hooks/useAppContext'
import { useCallback, useEffect } from 'react';

const { Title } = Typography;

const Home: NextPage = () => {
  const { animes, pageOffset, loadAnimes } = useAppData()
  
  const reloadAnimes = useCallback(() => {
    loadAnimes?.(pageOffset + 1)
  }, [loadAnimes, pageOffset])

  useEffect(() => {
    if(pageOffset === 0){
      reloadAnimes()
    }
  }, [reloadAnimes, pageOffset])

  return (
    <div>
      <Head>
        <title>Home - AnimeTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
        <Title>Fique por dentro do que há de melhor no mundo dos animes</Title>
        <CardGrid data={animes} />
        <Button
          type='primary'
          onClick={() => reloadAnimes()}>
            Veja mais
          </Button>
      </Layout>
    </div>
  )
}

export default Home
