import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/template/Layout'
import { Button, Typography } from 'antd';
import CardGrid from '../components/template/CardGrid';
import useAppData from '../data/hooks/useAppContext'
import { useEffect } from 'react';
import { PlusIcon } from '../components/icons';

const { Title } = Typography;

const Home: NextPage = () => {
  const { animes, pageOffset, loadAnimes } = useAppData()

  useEffect(() => {
    if(pageOffset === 0){
      loadAnimes?.(1)
    }
  }, [loadAnimes, pageOffset])

  return (
    <div>
      <Head>
        <title>Home - AnimeTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>
        <Title>The best of the anime world you find here</Title>
        <CardGrid data={animes} />
        <Button
          className='plus-btn'
          type='text'
          onClick={() => loadAnimes?.(pageOffset + 1)}>
            {PlusIcon}
          </Button>
      </Layout>
    </div>
  )
}

export default Home
